#!/bin/bash

echo "WARNING: This action will delete both local reference and remote instances."
read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    # obtain list of machines
    machine_names=$(docker-machine ls --format "{{.Name}}")
    while read -r machine; do
        docker-machine rm $machine -y
    done <<< $machine_names
fi
